package com.crud.hibernate.pojos;
// Generated 6/09/2017 03:31:34 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Tpersona generated by hbm2java
 */
public class Tpersona  implements java.io.Serializable {


     private Integer idPersona;
     private String dniPersona;
     private String nombrePersona;
     private String apellidoPaterno;
     private String apellidoMaterno;
     private Date fechaNacimiento;
     private boolean estado;

    public Tpersona() {
    }

    public Tpersona(String dniPersona, String nombrePersona, String apellidoPaterno, String apellidoMaterno, Date fechaNacimiento, boolean estado) {
       this.dniPersona = dniPersona;
       this.nombrePersona = nombrePersona;
       this.apellidoPaterno = apellidoPaterno;
       this.apellidoMaterno = apellidoMaterno;
       this.fechaNacimiento = fechaNacimiento;
       this.estado = estado;
    }
   
    public Integer getIdPersona() {
        return this.idPersona;
    }
    
    public void setIdPersona(Integer idPersona) {
        this.idPersona = idPersona;
    }
    public String getDniPersona() {
        return this.dniPersona;
    }
    
    public void setDniPersona(String dniPersona) {
        this.dniPersona = dniPersona;
    }
    public String getNombrePersona() {
        return this.nombrePersona;
    }
    
    public void setNombrePersona(String nombrePersona) {
        this.nombrePersona = nombrePersona;
    }
    public String getApellidoPaterno() {
        return this.apellidoPaterno;
    }
    
    public void setApellidoPaterno(String apellidoPaterno) {
        this.apellidoPaterno = apellidoPaterno;
    }
    public String getApellidoMaterno() {
        return this.apellidoMaterno;
    }
    
    public void setApellidoMaterno(String apellidoMaterno) {
        this.apellidoMaterno = apellidoMaterno;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }




}


